### ISSUE TITLE
Create a sample set of images of events

### ISSUE THREAD

**Issue by z3t0** [MFarabi619/hackthetunnels#13]
1. We need 10 images of events with some variation in the way the info in the image is written.
2. To start we can use screenshots, and then move onto phone pictures of posters/web pages
3. These images will be used to develop and test the image processing script.

**Comment by MFarabi619** [comment]
Sure, here are some screenshots.

![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/b3e714c2-8e1b-439b-b678-68bc2c36bdad)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/4bc92164-3b54-42c8-8753-a6b9f09db5a2)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/586dca4d-73a6-4c25-953e-208b5fd220a5)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/2e2f8192-b349-455d-b18b-99aba9831d7c)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/5c349f31-b72a-4879-86f0-0a7741d62faa)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/641272af-0f74-45a7-843f-4064626f45d7)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/871127a4-ab63-484c-996d-90d599efa806)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/e504ba0d-15c1-48a1-a199-a8cb289b42b3)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/9639b3a5-1c8a-4001-8c5a-cfcf6a8f8530)
![image](https://github.com/MFarabi619/hackthetunnels/assets/54924158/24715c20-b19c-4d99-bdd3-7305c0af73f4)
